# Task: Quantum Circuit Simulator

In [1]:
# Qubit in |0> state (100% probability of measuring 0)
q0 = [1, 0]

# Qubit in |1> state (100% probability of measuring 1)
q1 = [0, 1] 

# Qubit |+> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1)
q2 = [0.7071067811865475, 0.7071067811865475]

# Qubit |-> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1) with phase pi
q3 = [0.7071067811865475, -0.7071067811865475]

# Qubit |i> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1) with phase pi/2
q3 = [0.7071067811865475, 0+0.7071067811865475j]

# Qubit |-i> state (superposition: 50% probability of measuring 0 and 50% probability of measuring 1) with phase -pi/2
q4 = [0.7071067811865475, 0-0.7071067811865475j]

In [2]:
import numpy as np

q4 = np.array([0.7071067811865475+0j, 0-0.7071067811865475j])
p4 = np.abs(q4)**2
print(p4)

[0.5 0.5]


In [3]:
#State vector
# Qubit in |0> state (100% probability of measuring 0)
q0 = [1, 0]

# Qubit in |1> state (100% probability of measuring 1)
q1 = [0, 1] 

combined_state = np.kron(q0, q1)

print(combined_state)

[0 1 0 0]


In [4]:
import numpy as np

# Let's start with qubit in state |0> (100% probability of measuring 0)   

q0 = np.array([1, 0])

print("Initial state:\t", q0)

# Define X (NOT) gate:

X = np.array([
[0, 1],
[1, 0]
])

# Now apply X gate to a qubit (matrix-vector dot product):

q0 = np.dot(X, q0)

print("Final state:\t", q0)

Initial state:	 [1 0]
Final state:	 [0 1]


In [5]:
import numpy as np

# Let's start with qubit in state |0> (100% probability of measuring 0)
    
q0 = np.array([1, 0])

print("Initial state:\t", q0)

# Define H (Hadamard) gate:

H = np.array([
[1/np.sqrt(2), 1/np.sqrt(2)],
[1/np.sqrt(2), -1/np.sqrt(2)]
])

# Now apply H gate to a qubit (matrix-vector dot product):

q0 = np.dot(H, q0)

print("Final state:\t", q0)

Initial state:	 [1 0]
Final state:	 [0.70710678 0.70710678]


In [6]:
import numpy as np

# Let's define state vector of the 3-qubit circuit in "ground state" (all qubits in state |0>)

psi = [1, 0, 0, 0, 0, 0, 0, 0]
print("Initial state:", psi)


# Define X (NOT) gate:

X = np.array([
[0, 1],
[1, 0]
])

# Define 2x2 identity

I = np.identity(2)

# Calculate operator for X gate acting on third qubit in 3-qubit circuit

O = np.kron(np.kron(I, I), X)

print("\nOperator:\n\n", O, "\n")


# And finally, apply operator

psi = np.dot(psi, O)
print("Final state:", psi)

Initial state: [1, 0, 0, 0, 0, 0, 0, 0]

Operator:

 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]] 

Final state: [0. 1. 0. 0. 0. 0. 0. 0.]


In [7]:
import numpy as np

# Define X gate (CNOT is controlled-X):

X = np.array([
[0, 1],
[1, 0]
])

# Define 2x2 Identity

I = np.identity(2)


# Define projection operator |0><0|

P0x0 = np.array([
[1, 0],
[0, 0]
])

# Define projection operator |1><1|

P1x1 = np.array([
[0, 0],
[0, 1]
])

# And now calculate our operator:

O = np.kron(np.kron(P0x0, I), I) + np.kron(np.kron(P1x1, I), X)

print("CNOT(0, 2) for 3-qubit circuit, operator is:\n")
print(O)

CNOT(0, 2) for 3-qubit circuit, operator is:

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In [18]:
def get_ground_state(num_qubits):
#Simulator program
    # return vector of size 2**num_qubits with all zeroes except first element which is 1
    return

def get_operator(total_qubits, gate_unitary, target_qubits):
    # return unitary operator of size 2**n x 2**n for given gate and target qubits
    return

def run_program(initial_state, program):
    # read program, and for each gate:
    #   - calculate matrix operator
    #   - multiply state with operator
    # return final state
    return

def measure_all(state_vector):
    # choose element from state_vector using weighted random and return it's index
    return

def get_counts(state_vector, num_shots):
    # simply execute measure_all in a loop num_shots times and
    # return object with statistics in following form:
    #   {
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      ...
    #   }
    # (only for elements which occoured - returned from measure_all)
    return

In [19]:
# Define program:

my_circuit = [
{ "gate": "h", "target": [0] }, 
{ "gate": "cx", "target": [0, 1] }
]


# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit)

#Measure circuit

#measure_alll = measure_all(final_state)

# Read results

counts = get_counts(final_state, 1000)

print(counts)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }

None


In [14]:
# Define program:

my_circuit = [
  { "unitary": [[0.70710678, 0.70710678], [0.70710678, -0.70710678]], "target": [0] }, 
  { "unitary": [ [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0] ], "target": [0, 1] }
  
]


# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit)


# Read results

counts = get_counts(final_state, 1000)

print(counts)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }

None


In [ ]:
#Parametric gates
# Define program:

my_circuit = [
  ["cos(theta/2)", "-exp(i * lambda) * sin(theta / 2)"],
  ["exp(i * phi) * sin(theta / 2)", "exp(i * lambda + i * phi) * cos(theta / 2)"]
]

# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit)


# Read results

counts = get_counts(final_state, 1000)

print(counts)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }

In [ ]:
#Parametric gates
# Define program:

my_circuit = [
  { "unitary": [["cos(theta/2)", "-exp(i * lambda) * sin(theta / 2)"], ["exp(i * phi) * sin(theta / 2)", "exp(i * lambda + i * phi) * cos(theta / 2)"]], "params": { "theta": 3.1415, "phi": 1.15708, "lambda": -3.1415 }, "target": [0] }
  
]
# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit)


# Read results

counts = get_counts(final_state, 1000)

print(counts)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }

In [ ]:
#Parametric gates
# Define program:

my_circuit = [
  { "gate": "u3", "params": { "theta": 3.1415, "phi": 1.5708, "lambda": -3.1415 }, "target": [0] }
  
]
# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit)


# Read results

counts = get_counts(final_state, 1000)

print(counts)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }

In [ ]:
#Allow running variational quantum algorithms
#Parametric gates
# Define program:

my_circuit = [
  { "gate": "u3", "params": { "theta": "global_1", "phi": "global_2", "lambda": -3.1415 }, "target": [0] }
  
]
# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit, { "global_1": 3.1415, "global_2": 1.5708 })


# Read results

counts = get_counts(final_state, 1000)

print(counts)

def objective_function(params):
    final_state = run_program(my_qpu, my_circuit, { "global_1": params[0], "global_2": params[1] })

    counts = get_counts(final_state, 1000)

    # ...calculate cost here...

    return cost

# initial values
params = np.array([3.1415, 1.5708])

# minimize
minimum = minimize(objective_function, params, method="Powell", tol=1e-6)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }